version: '3.6'
services:
  stats:
    image: virtualzone/docker-container-stats
    container_name: 'stats'
    ports:
      - '8080:8080'
    environment:
      STATS_UPDATE_INTERVAL: 10
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/home/docker/storage/stats/db:/opt/docker-stats/db'
